### ISSUE TITLE
"export 'FeatureFlipping' was not found in 'vue-feature-flipping'

### ISSUE THREAD

**Issue by gioppoluca** [pinguet62/vue-feature-flipping#8]
I'm trying to use this component in a quasar project.

Quasar version Pkg @quasar/app... v1.2.4

Followed the doc and imported 
`import { FeatureFlipping } from 'vue-feature-flipping'

Vue.use(FeatureFlipping)
`
Any hints?

**Comment by pinguet62** [comment]
👋 *Thanks for the interest in my project*

Please try the **default import** `import FeatureFlipping from 'vue-feature-flipping'`

**Comment by gioppoluca** [comment]
same result different error:
`"export 'default' (imported as 'FeatureFlipping') was not found in 'vue-feature-flipping'`

**Comment by pinguet62** [comment]
*Wrong packaging on my side...* 👼
Please could you retry with new version `2.1.0`
